name: massa sc ci tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install
        working-directory: ./smart-contract
        run: npm ci
      - name: Test
        working-directory: ./smart-contract
        run: npm run test
