name: DeWeb deployer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: coin-vester-front/package-lock.json

      - name: Install
        run: npm ci
        working-directory: coin-vester-front

      - name: Build
        run: npm run build
        working-directory: coin-vester-front

      - name: Deploy to Massa DeWeb
        id: deploy
        uses: massalabs/deweb-gh-action@v0.0.7
        with:
          config_file: coin-vester-front/deweb_cli_config.mainnet.json
          source_folder: coin-vester-front/dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: Get deployed website address
        run: |
          echo "Deployed website address: ${{ steps.deploy.outputs.deployed-website }}"